version: '3' 

services:
  spark-master:
    image: bde2020/spark-master:$SPARK_VERSION
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment: 
      - PYSPARK_PYTHON=python3
    env_file:
      - ./hadoop.env

  spark-worker1:
    image: bde2020/spark-worker:$SPARK_VERSION
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    # ports:
    #   - 8081:8081
    env_file:
      - ./hadoop.env
  
  spark-worker2:
    image: bde2020/spark-worker:$SPARK_VERSION
    container_name: spark-worker2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    # ports:
    #   - 8082:8081
    env_file:
      - ./hadoop.env