version: "3"

services:
  bitcoin-node:
    image: ruimarinho/bitcoin-core
    container_name: bitcoin-node
    volumes: 
      - ./bitcoin-node:/home/scripts/
      - bitcoin_data:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
      - 8333:8333
    command: "-prune=550 -printtoconsole -rpcallowip=::/0 -blocknotify='/home/scripts/transaction.sh %s' -rpcbind=0.0.0.0 -rpcauth=foo:7d9ba5ae63c3d4dc30583ff4fe65a67e$$9e3634e81c11659e3de036d0bf88f89cd169c1039e6e09607562d54765c649cc"

  ethereum-node:
    image: ethereum/client-go
    container_name: ethereum-node
    volumes: 
      - ethereum_data:/root
    ports: 
      - 8545:8545
      - 30303:30303
    command: "--rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --syncmode light"
  
  btc-producer:
    build: ./producers/bitcoin
    container_name: btc-producer
    ports:
      - 8081:80
    environment:
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - bitcoin-node
      - kafka1

  eth-producer:
    build: ./producers/ethereum
    container_name: eth-producer
    environment: 
      WEB3_PROVIDER_URI: "http://ethereum-node:8545"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - ethereum-node
      - kafka1

  twitter-producer:
    build: ./producers/twitter
    container_name: twitter-producer
    env_file: 
      - ./producers/twitter/auth.env
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TRACKS: bitcoin,ethereum
    depends_on:
      - kafka1

  reddit-producer:
    build: ./producers/reddit
    container_name: reddit-producer
    env_file: 
      - ./producers/reddit/auth.env
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      SUBREDDITS: bitcoin,ethereum
    depends_on:
      - kafka1

  exchange-rate-producer:
    build: ./producers/exchange-rate
    container_name: exchange-rate-producer
    env_file: 
      - ./producers/exchange-rate/auth.env
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on:
      - kafka1

  stream-processor:
    image: maven:3.6.3-jdk-8-openj9
    container_name: stream-processor
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    volumes: 
      - ./stream-processing:/home/stream-processing
    command: "/home/stream-processing/run.sh"
  
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports: 
      - 3000:3000

volumes: 
  bitcoin_data:
  ethereum_data: