version: "3"

services:
  bitcoin-node:
    image: ruimarinho/bitcoin-core
    container_name: bitcoin-node
    volumes: 
      - ./bitcoin-node:/home/scripts/
      - bitcoin_data:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
      - 8333:8333
    command: "-prune=550 -printtoconsole -rpcallowip=::/0 -blocknotify='/home/scripts/transaction.sh %s' -rpcbind=0.0.0.0 -rpcauth=foo:7d9ba5ae63c3d4dc30583ff4fe65a67e$$9e3634e81c11659e3de036d0bf88f89cd169c1039e6e09607562d54765c649cc"

  ethereum-node:
    image: ethereum/client-go
    container_name: ethereum-node
    volumes: 
      - ethereum_data:/root
    ports: 
      - 8545:8545
      - 30303:30303
    command: "--rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --syncmode light"
  
  btc-producer:
    build: ./btc-producer
    container_name: btc-producer
    ports:
      - 8081:80
    environment:
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - bitcoin-node
      - kafka1

  eth-producer:
    build: ./eth-producer
    container_name: eth-producer
    environment: 
      WEB3_PROVIDER_URI: "http://ethereum-node:8545"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - ethereum-node
      - kafka1

  twitter-producer:
    build: ./twitter
    container_name: twitter-producer
    env_file: 
      - ./twitter/auth.env
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on:
      - kafka1
  
  btc-consumer:
    build: ./basic-consumer
    container_name: btc-consumer
    command: "btc-app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - btc-producer
      - namenode

  eth-consumer:
    build: ./basic-consumer
    container_name: eth-consumer
    command: "eth-app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    depends_on: 
      - eth-producer
      - namenode

  stream-processor:
    image: maven:3.6.3-jdk-8-openj9
    container_name: stream-processor
    environment: 
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
    volumes: 
      - ./stream-processing:/home/stream-processing
    command: "/home/stream-processing/run.sh"

volumes: 
  bitcoin_data:
  ethereum_data: