version: "3"

services:
  btc-consumer:
    build: ./consumers
    container_name: btc-consumer
    command: "app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TOPIC: "btc-block"
      MAX_RECORDS: 1
      SCHEMA_FILE: "bitcoin/block.avsc"
    depends_on: 
      - btc-producer
      - namenode
    
  eth-consumer:
    build: ./consumers
    container_name: eth-consumer
    command: "app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TOPIC: "eth-block"
      MAX_RECORDS: 20
      SCHEMA_FILE: "ethereum/block.avsc"
    depends_on: 
      - eth-producer
      - namenode

  exchange-rate-consumer:
    build: ./consumers
    container_name: exchange-rate-consumer
    command: "app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TOPIC: "exchange-rates"
      MAX_RECORDS: 200
      SCHEMA_FILE: "exchange-rate/record.avsc"
    depends_on: 
      - exchange-rate-producer
      - namenode

  reddit-btc-consumer:
    build: ./consumers
    container_name: reddit-btc-consumer
    command: "app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TOPIC: "subreddit-Bitcoin"
      MAX_RECORDS: 25
      SCHEMA_FILE: "reddit/comment.avsc"
    depends_on: 
      - reddit-producer
      - namenode

  reddit-eth-consumer:
    build: ./consumers
    container_name: reddit-eth-consumer
    command: "app.py"
    environment:
      HDFS_HOST: "http://namenode:9870"
      KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
      TOPIC: "subreddit-ethereum"
      MAX_RECORDS: 5
      SCHEMA_FILE: "reddit/comment.avsc"
    depends_on: 
      - reddit-producer
      - namenode

### TWITTER