version: "3"

services:  
    btc-producer:
        build: ./producers/bitcoin
        container_name: btc-producer
        ports:
            - 8081:80
        environment:
            KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
        depends_on: 
            - bitcoin-node
            - kafka1

    eth-producer:
        build: ./producers/ethereum
        container_name: eth-producer
        environment: 
            WEB3_PROVIDER_URI: "http://ethereum-node:8545"
            KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
        depends_on: 
            - ethereum-node
            - kafka1

    twitter-producer:
        build: ./producers/twitter
        container_name: twitter-producer
        env_file: 
            - ./producers/twitter/auth.env
        environment: 
            KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
            TRACKS: bitcoin,ethereum
        depends_on:
            - kafka1

    reddit-producer:
        build: ./producers/reddit
        container_name: reddit-producer
        env_file: 
            - ./producers/reddit/auth.env
        environment: 
            KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
            SUBREDDITS: bitcoin,ethereum
        depends_on:
            - kafka1

    exchange-rate-producer:
        build: ./producers/exchange-rate
        container_name: exchange-rate-producer
        env_file: 
            - ./producers/exchange-rate/auth.env
        environment: 
            KAFKA_BROKER: "kafka1:19092,kafka2:19092,kafka3:19092"
        depends_on:
            - kafka1
    